/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAlert: typeof import('ant-design-vue/es')['Alert']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AddModule: (typeof import('./src/components/button/AddModule.vue'))['default']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: (typeof import('ant-design-vue/es'))['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: (typeof import('ant-design-vue/es'))['InputPassword']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: (typeof import('ant-design-vue/es'))['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATabPane: (typeof import('ant-design-vue/es'))['TabPane']
    ATabs: (typeof import('ant-design-vue/es'))['Tabs']
    BatchDelete: (typeof import('./src/components/button/BatchDelete.vue'))['default']
    Button: typeof import('./src/components/button/button.vue')['default']
    Columns: (typeof import('./src/components/table/columns.vue'))['default']
    ColumnsOperation: typeof import('./src/components/table/columns-operation.vue')['default']
    Form: typeof import('./src/components/form/form.vue')['default']
    Headers: typeof import('./src/components/header/headers.vue')['default']
    Ipopover: (typeof import('./src/components/header/Ipopover.vue'))['default']
    Modal: typeof import('./src/components/modal/modal.vue')['default']
    NotFound: typeof import('./src/components/not-found/not-found.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/table/table.vue')['default']
    ToggleDark: typeof import('./src/components/switch/toggleDark.vue')['default']
    TwoStepCaptcha: (typeof import('./src/components/tools/TwoStepCaptcha.vue'))['default']
  }
}
